import type { ScanContent } from "./type/ScanContent.js";
import { mergeToPdf } from "./pdfProcessing.js";
import {
  convertImagesToPdfAndUploadAsSeparateDocumentsToPaperless,
  mergeToPdfAndUploadAsSingleDocumentToPaperless,
  uploadImagesAsSeparateDocumentsToPaperless,
  uploadPdfToPaperless,
} from "./paperless/paperless.js";
import {
  uploadPdfToNextcloud,
  uploadImagesToNextcloud,
  nextcloudWebdavFileUrl,
} from "./nextcloud/nextcloud.js";
import { uploadPdfToS3, uploadImagesToS3, s3ObjectLocation } from "./s3/s3.js";
import {
  sendScanEvent,
  type WebhookDeliveryTarget,
  type WebhookFileSource,
} from "./webhook/webhook.js";
import type { WebhookConfig } from "./webhook/WebhookConfig.js";
import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import type { PaperlessConfig } from "./paperless/PaperlessConfig.js";
import type { NextcloudConfig } from "./nextcloud/NextcloudConfig.js";
import type { S3Config } from "./s3/S3Config.js";
import type { ScanConfig } from "./type/scanConfigs.js";
import { getLoggerForFile } from "./logger.js";

const logger = getLoggerForFile(import.meta.url);

export interface PostProcessingResult {
  uploadSucceeded: boolean;
  failures: string[];
}

/**
 * Mutable state threaded through every post-processing stage. Each stage fills
 * in the fields it owns; the orchestrator returns the outcome once all stages
 * have run.
 */
export interface ProcessingStageContext {
  scanConfig: ScanConfig;
  folder: string;
  tempFolder: string;
  scanCount: number;
  scanJobContent: ScanContent;
  scanDate: Date;
  toPdf: boolean;
  /** PDF generated by the pdf-merge stage (null when toPdf is false or merge failed). */
  pdfFilePath: string | null;
  failures: string[];
  delivery: WebhookDeliveryTarget[];
}

export type ProcessingStage = (
  ctx: ProcessingStageContext,
) => Promise<void> | void;

function toFailureMessage(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

async function recordDelivery(
  delivery: WebhookDeliveryTarget[],
  failures: string[],
  target: string,
  action: () => Promise<void>,
): Promise<void> {
  try {
    await action();
    delivery.push({ target, status: "success", error: undefined });
  } catch (e) {
    const message = toFailureMessage(e);
    failures.push(message);
    delivery.push({ target, status: "failed", error: message });
  }
}

function deliverySucceeded(
  delivery: WebhookDeliveryTarget[],
  target: string,
): boolean {
  return delivery.some((d) => d.target === target && d.status === "success");
}

function buildWebhookFileSource(
  file: { path: string; contentType?: string },
  s3Config: S3Config | undefined,
  nextcloudConfig: NextcloudConfig | undefined,
  delivery: WebhookDeliveryTarget[],
): WebhookFileSource {
  const source: WebhookFileSource = { path: file.path };
  if (file.contentType !== undefined) {
    source.contentType = file.contentType;
  }
  // Only advertise a remote location the file was actually delivered to,
  // otherwise consumers would be pointed at objects that do not exist.
  if (s3Config && deliverySucceeded(delivery, "s3")) {
    source.store = "s3";
    source.location = s3ObjectLocation(s3Config, path.basename(file.path));
  } else if (nextcloudConfig && deliverySucceeded(delivery, "nextcloud")) {
    source.store = "nextcloud";
    source.location = {
      webdavUrl: nextcloudWebdavFileUrl(
        nextcloudConfig,
        path.basename(file.path),
      ),
    };
  }
  return source;
}

/**
 * First stage: produce the merged PDF when the scan target is a PDF.
 * Future pre-processing stages (OCR, deskew, an external `--post-command`)
 * plug in BEFORE this one, once they operate on the captured pages.
 */
async function generatePdfStage(ctx: ProcessingStageContext): Promise<void> {
  if (!ctx.toPdf) {
    return;
  }
  const paperlessConfig = ctx.scanConfig.paperlessConfig;
  const pdfFilePath = await mergeToPdf(
    paperlessConfig ? ctx.tempFolder : ctx.folder,
    ctx.scanCount,
    ctx.scanJobContent,
    ctx.scanConfig.directoryConfig.filePattern,
    ctx.scanDate,
    true,
  );
  ctx.pdfFilePath = pdfFilePath;
  if (pdfFilePath !== null) {
    ctx.delivery.push({ target: "pdf", status: "success", error: undefined });
  } else {
    ctx.delivery.push({
      target: "pdf",
      status: "failed",
      error: "PDF generation failed, nothing was uploaded",
    });
  }
}

/** Announce which output was produced (PDF or individual images). */
function announceStage(ctx: ProcessingStageContext): void {
  if (ctx.toPdf) {
    displayPdfScan(ctx.pdfFilePath, ctx.scanJobContent, ctx.scanCount);
  } else {
    displayImageScan(ctx.scanJobContent, ctx.scanCount);
  }
}

/** Upload to every configured delivery target (paperless / nextcloud / S3). */
async function deliverStage(ctx: ProcessingStageContext): Promise<void> {
  const { scanConfig, scanJobContent, folder, scanCount, scanDate, delivery, failures } =
    ctx;
  const paperlessConfig = scanConfig.paperlessConfig;
  const nextcloudConfig = scanConfig.nextcloudConfig;
  const s3Config = scanConfig.s3Config;

  if (ctx.toPdf) {
    const pdfFilePath = ctx.pdfFilePath;
    if (pdfFilePath !== null) {
      if (paperlessConfig) {
        await recordDelivery(delivery, failures, "paperless", () =>
          uploadPdfToPaperless(pdfFilePath, paperlessConfig),
        );
      }
      if (nextcloudConfig) {
        await recordDelivery(delivery, failures, "nextcloud", () =>
          uploadPdfToNextcloud(pdfFilePath, nextcloudConfig),
        );
      }
      if (s3Config) {
        await recordDelivery(delivery, failures, "s3", () =>
          uploadPdfToS3(pdfFilePath, s3Config),
        );
      }
    }
  } else {
    if (paperlessConfig) {
      await recordDelivery(delivery, failures, "paperless", () =>
        handlePaperlessImageDelivery(
          folder,
          scanCount,
          scanJobContent,
          scanConfig,
          scanDate,
          paperlessConfig,
        ),
      );
    }
    if (nextcloudConfig) {
      await recordDelivery(delivery, failures, "nextcloud", () =>
        uploadImagesToNextcloud(scanJobContent, nextcloudConfig),
      );
    }
    if (s3Config) {
      await recordDelivery(delivery, failures, "s3", () =>
        uploadImagesToS3(scanJobContent, s3Config),
      );
    }
  }
}

/** Notify the webhook about the completed scan and its delivery outcome. */
async function webhookStage(ctx: ProcessingStageContext): Promise<void> {
  const webhookConfig = ctx.scanConfig.webhookConfig;
  if (!webhookConfig) {
    return;
  }
  const s3Config = ctx.scanConfig.s3Config;
  const nextcloudConfig = ctx.scanConfig.nextcloudConfig;

  if (ctx.toPdf) {
    const pdfFilePath = ctx.pdfFilePath;
    await sendScanEvent(
      ctx.scanJobContent,
      pdfFilePath !== null
        ? [
            buildWebhookFileSource(
              { path: pdfFilePath, contentType: "application/pdf" },
              s3Config,
              nextcloudConfig,
              ctx.delivery,
            ),
          ]
        : [],
      ctx.delivery,
      webhookConfig,
    );
  } else {
    await sendScanEvent(
      ctx.scanJobContent,
      ctx.scanJobContent.elements.map((element) =>
        buildWebhookFileSource(
          {
            path: element.path,
            ...(element.contentType !== undefined
              ? { contentType: element.contentType }
              : {}),
          },
          s3Config,
          nextcloudConfig,
          ctx.delivery,
        ),
      ),
      ctx.delivery,
      webhookConfig,
    );
  }
}

/** Emit the scan metadata summary (sizes, timings, job state). */
async function logMetadataStage(ctx: ProcessingStageContext): Promise<void> {
  await logScanMetadata(ctx.scanJobContent, ctx.scanDate);
}

/**
 * Last stage: decide whether to keep the files based on keepFiles. Only runs
 * when every delivery succeeded, so a failed upload keeps its files locally.
 */
async function cleanupStage(ctx: ProcessingStageContext): Promise<void> {
  const { paperlessConfig, nextcloudConfig, s3Config, webhookConfig } =
    ctx.scanConfig;

  if (ctx.toPdf) {
    if (ctx.failures.length === 0 && ctx.pdfFilePath !== null) {
      await cleanUpFilesIfNeeded(
        [ctx.pdfFilePath],
        paperlessConfig,
        nextcloudConfig,
        s3Config,
        webhookConfig,
      );
    }
  } else {
    if (ctx.failures.length === 0) {
      const filePaths = ctx.scanJobContent.elements.map((element) => element.path);
      await cleanUpFilesIfNeeded(
        filePaths,
        paperlessConfig,
        nextcloudConfig,
        s3Config,
        webhookConfig,
      );
    }
  }
}

const postProcessingStages: ProcessingStage[] = [
  // Pre-processing stages (external OCR/deskew/`--post-command`) are inserted
  // here, before the PDF merge, once they operate on the captured pages.
  generatePdfStage,
  announceStage,
  deliverStage,
  webhookStage,
  logMetadataStage,
  cleanupStage,
];

export async function postProcessing(
  scanConfig: ScanConfig,
  folder: string,
  tempFolder: string,
  scanCount: number,
  scanJobContent: ScanContent,
  scanDate: Date,
  toPdf: boolean,
): Promise<PostProcessingResult> {
  const ctx: ProcessingStageContext = {
    scanConfig,
    folder,
    tempFolder,
    scanCount,
    scanJobContent,
    scanDate,
    toPdf,
    pdfFilePath: null,
    failures: [],
    delivery: [],
  };

  for (const stage of postProcessingStages) {
    await Promise.resolve(stage(ctx));
  }

  return { uploadSucceeded: ctx.failures.length === 0, failures: ctx.failures };
}

async function handlePaperlessImageDelivery(
  folder: string,
  scanCount: number,
  scanJobContent: ScanContent,
  scanConfig: ScanConfig,
  scanDate: Date,
  paperlessConfig: PaperlessConfig,
): Promise<void> {
  if (paperlessConfig.groupMultiPageScanIntoAPdf) {
    await mergeToPdfAndUploadAsSingleDocumentToPaperless(
      folder,
      scanCount,
      scanJobContent,
      scanConfig,
      scanDate,
      paperlessConfig,
    );
  } else {
    if (paperlessConfig.alwaysSendAsPdfFile) {
      await convertImagesToPdfAndUploadAsSeparateDocumentsToPaperless(
        scanJobContent,
        paperlessConfig,
        scanDate,
      );
    } else {
      await uploadImagesAsSeparateDocumentsToPaperless(
        scanJobContent,
        paperlessConfig,
      );
    }
  }
}

async function logScanMetadata(
  scanJobContent: ScanContent,
  scanDate: Date,
): Promise<void> {
  const meta = scanJobContent.meta;
  if (meta === undefined) {
    return;
  }
  const pages = await Promise.all(
    scanJobContent.elements.map(async (element) => {
      let sizeBytes: number | undefined;
      try {
        sizeBytes = (await fs.stat(element.path)).size;
      } catch {
        sizeBytes = undefined;
      }
      return {
        pageNumber: element.pageNumber,
        path: element.path,
        format: path.extname(element.path).replace(/^\./, ""),
        width: element.width,
        height: element.height,
        xResolution: element.xResolution,
        yResolution: element.yResolution,
        sizeBytes,
        capturedAt: element.capturedAt,
        durationMs: element.durationMs,
        contentType: element.contentType,
      };
    }),
  );
  logger.info(
    {
      metadata: {
        ...meta,
        endedAt: new Date().toISOString(),
        durationMs: Date.now() - scanDate.getTime(),
      },
      pages,
    },
    "Scan completed",
  );
}

function displayPdfScan(
  pdfFilePath: string | null,
  scanJobContent: ScanContent,
  scanCount: number,
) {
  if (pdfFilePath === null) {
    logger.warn(`Pdf generated has not been generated`);
    return;
  }

  logger.info(
    `Scan #${scanCount} saved as PDF: ${pdfFilePath} with the following pages:`,
  );
  scanJobContent.elements.forEach((e) =>
    logger.info(
      `\t- page ${e.pageNumber.toString().padStart(3, " ")} | ${e.width}x${
        e.height
      } | (temp file deleted ${e.path})`,
    ),
  );
}

function displayImageScan(scanJobContent: ScanContent, scanCount: number) {
  logger.info(`Scan #${scanCount} completed with the following pages:`);
  scanJobContent.elements.forEach((e) =>
    logger.info(
      `\t- page ${e.pageNumber.toString().padStart(3, " ")} | ${e.width}x${
        e.height
      } | ${e.path}`,
    ),
  );
}

async function cleanUpFilesIfNeeded(
  filePaths: string[],
  paperlessConfig: PaperlessConfig | undefined,
  nextcloudConfig: NextcloudConfig | undefined,
  s3Config: S3Config | undefined,
  webhookConfig: WebhookConfig | undefined,
) {
  const keepFiles: boolean =
    paperlessConfig?.keepFiles ??
    nextcloudConfig?.keepFiles ??
    s3Config?.keepFiles ??
    webhookConfig?.keepFiles ??
    true;
  if (!keepFiles) {
    await Promise.all(
      filePaths.map(async (filePath) => {
        if (existsSync(filePath)) {
          await fs.unlink(filePath);
          logger.info(`File ${filePath} has been removed from the filesystem`);
        } else {
          logger.warn(
            `File ${filePath} was already removed from the filesystem`,
          );
        }
      }),
    );
  }
}