import type { ScanContent } from "./type/ScanContent.js";
import { mergeToPdf } from "./pdfProcessing.js";
import {
  convertImagesToPdfAndUploadAsSeparateDocumentsToPaperless,
  mergeToPdfAndUploadAsSingleDocumentToPaperless,
  uploadImagesAsSeparateDocumentsToPaperless,
  uploadPdfToPaperless,
} from "./paperless/paperless.js";
import {
  uploadPdfToNextcloud,
  uploadImagesToNextcloud,
} from "./nextcloud/nextcloud.js";
import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import type { PaperlessConfig } from "./paperless/PaperlessConfig.js";
import type { NextcloudConfig } from "./nextcloud/NextcloudConfig.js";
import type { ScanConfig } from "./type/scanConfigs.js";
import { getLoggerForFile } from "./logger.js";

const logger = getLoggerForFile(import.meta.url);

export interface PostProcessingResult {
  uploadSucceeded: boolean;
  failures: string[];
}

/**
 * Mutable state threaded through every post-processing stage. Each stage fills
 * in the fields it owns; the orchestrator returns the outcome once all stages
 * have run.
 */
export interface ProcessingStageContext {
  scanConfig: ScanConfig;
  folder: string;
  tempFolder: string;
  scanCount: number;
  scanJobContent: ScanContent;
  scanDate: Date;
  toPdf: boolean;
  /** PDF generated by the pdf-merge stage (null when toPdf is false or merge failed). */
  pdfFilePath: string | null;
  failures: string[];
}

export type ProcessingStage = (
  ctx: ProcessingStageContext,
) => Promise<void> | void;

function toFailureMessage(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

/**
 * First stage: produce the merged PDF when the scan target is a PDF.
 * Future pre-processing stages (OCR, deskew, an external `--post-command`)
 * plug in BEFORE this one, once they operate on the captured pages.
 */
async function generatePdfStage(ctx: ProcessingStageContext): Promise<void> {
  if (!ctx.toPdf) {
    return;
  }
  const paperlessConfig = ctx.scanConfig.paperlessConfig;
  ctx.pdfFilePath = await mergeToPdf(
    paperlessConfig ? ctx.tempFolder : ctx.folder,
    ctx.scanCount,
    ctx.scanJobContent,
    ctx.scanConfig.directoryConfig.filePattern,
    ctx.scanDate,
    true,
  );
}

/** Announce which output was produced (PDF or individual images). */
function announceStage(ctx: ProcessingStageContext): void {
  if (ctx.toPdf) {
    displayPdfScan(ctx.pdfFilePath, ctx.scanJobContent, ctx.scanCount);
  } else {
    displayImageScan(ctx.scanJobContent, ctx.scanCount);
  }
}

/** Upload to every configured delivery target (paperless / nextcloud). */
async function deliverStage(ctx: ProcessingStageContext): Promise<void> {
  const { scanConfig, scanJobContent, folder, scanCount, scanDate, failures } =
    ctx;
  const paperlessConfig = scanConfig.paperlessConfig;
  const nextcloudConfig = scanConfig.nextcloudConfig;

  if (ctx.toPdf) {
    const pdfFilePath = ctx.pdfFilePath;
    if (pdfFilePath !== null) {
      if (paperlessConfig) {
        try {
          await uploadPdfToPaperless(pdfFilePath, paperlessConfig);
        } catch (e) {
          failures.push(toFailureMessage(e));
        }
      }
      if (nextcloudConfig) {
        try {
          await uploadPdfToNextcloud(pdfFilePath, nextcloudConfig);
        } catch (e) {
          failures.push(toFailureMessage(e));
        }
      }
    }
  } else {
    if (paperlessConfig) {
      try {
        await handlePaperlessImageDelivery(
          folder,
          scanCount,
          scanJobContent,
          scanConfig,
          scanDate,
          paperlessConfig,
        );
      } catch (e) {
        failures.push(toFailureMessage(e));
      }
    }
    if (nextcloudConfig) {
      try {
        await uploadImagesToNextcloud(scanJobContent, nextcloudConfig);
      } catch (e) {
        failures.push(toFailureMessage(e));
      }
    }
  }
}

/**
 * Last stage: decide whether to keep the files based on keepFiles. Only runs
 * when every delivery succeeded, so a failed upload keeps its files locally.
 */
async function cleanupStage(ctx: ProcessingStageContext): Promise<void> {
  const { paperlessConfig, nextcloudConfig } = ctx.scanConfig;

  if (ctx.toPdf) {
    if (ctx.failures.length === 0 && ctx.pdfFilePath !== null) {
      await cleanUpFilesIfNeeded(
        [ctx.pdfFilePath],
        paperlessConfig,
        nextcloudConfig,
      );
    }
  } else {
    if (ctx.failures.length === 0) {
      const filePaths = ctx.scanJobContent.elements.map((element) => element.path);
      await cleanUpFilesIfNeeded(
        filePaths,
        paperlessConfig,
        nextcloudConfig,
      );
    }
  }
}

const postProcessingStages: ProcessingStage[] = [
  // Pre-processing stages (external OCR/deskew/`--post-command`) are inserted
  // here, before the PDF merge, once they operate on the captured pages.
  generatePdfStage,
  announceStage,
  deliverStage,
  cleanupStage,
];

export async function postProcessing(
  scanConfig: ScanConfig,
  folder: string,
  tempFolder: string,
  scanCount: number,
  scanJobContent: ScanContent,
  scanDate: Date,
  toPdf: boolean,
): Promise<PostProcessingResult> {
  const ctx: ProcessingStageContext = {
    scanConfig,
    folder,
    tempFolder,
    scanCount,
    scanJobContent,
    scanDate,
    toPdf,
    pdfFilePath: null,
    failures: [],
  };

  for (const stage of postProcessingStages) {
    await Promise.resolve(stage(ctx));
  }

  return { uploadSucceeded: ctx.failures.length === 0, failures: ctx.failures };
}

async function handlePaperlessImageDelivery(
  folder: string,
  scanCount: number,
  scanJobContent: ScanContent,
  scanConfig: ScanConfig,
  scanDate: Date,
  paperlessConfig: PaperlessConfig,
): Promise<void> {
  if (paperlessConfig.groupMultiPageScanIntoAPdf) {
    await mergeToPdfAndUploadAsSingleDocumentToPaperless(
      folder,
      scanCount,
      scanJobContent,
      scanConfig,
      scanDate,
      paperlessConfig,
    );
  } else {
    if (paperlessConfig.alwaysSendAsPdfFile) {
      await convertImagesToPdfAndUploadAsSeparateDocumentsToPaperless(
        scanJobContent,
        paperlessConfig,
        scanDate,
      );
    } else {
      await uploadImagesAsSeparateDocumentsToPaperless(
        scanJobContent,
        paperlessConfig,
      );
    }
  }
}

function displayPdfScan(
  pdfFilePath: string | null,
  scanJobContent: ScanContent,
  scanCount: number,
) {
  if (pdfFilePath === null) {
    logger.warn(`Pdf generated has not been generated`);
    return;
  }

  logger.info(
    `Scan #${scanCount} saved as PDF: ${pdfFilePath} with the following pages:`,
  );
  scanJobContent.elements.forEach((e) =>
    logger.info(
      `\t- page ${e.pageNumber.toString().padStart(3, " ")} | ${e.width}x${
        e.height
      } | (temp file deleted ${e.path})`,
    ),
  );
}

function displayImageScan(scanJobContent: ScanContent, scanCount: number) {
  logger.info(`Scan #${scanCount} completed with the following pages:`);
  scanJobContent.elements.forEach((e) =>
    logger.info(
      `\t- page ${e.pageNumber.toString().padStart(3, " ")} | ${e.width}x${
        e.height
      } | ${e.path}`,
    ),
  );
}

async function cleanUpFilesIfNeeded(
  filePaths: string[],
  paperlessConfig: PaperlessConfig | undefined,
  nextcloudConfig: NextcloudConfig | undefined,
) {
  const keepFiles: boolean =
    paperlessConfig?.keepFiles ?? nextcloudConfig?.keepFiles ?? true;
  if (!keepFiles) {
    await Promise.all(
      filePaths.map(async (filePath) => {
        if (existsSync(filePath)) {
          await fs.unlink(filePath);
          logger.info(`File ${filePath} has been removed from the filesystem`);
        } else {
          logger.warn(
            `File ${filePath} was already removed from the filesystem`,
          );
        }
      }),
    );
  }
}